[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fundraiser = "6HxECZB3LaJttGbndvtjgUkFu6cJLRDEdag3V58hXqrs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vinhtrinhvan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
